package com.point.db.model;

public class CameraHotRelationDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_hot_relation.target_id
     *
     * @mbg.generated
     */
    private Long targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_hot_relation.target_id1
     *
     * @mbg.generated
     */
    private Long targetId1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_hot_relation.target_id2
     *
     * @mbg.generated
     */
    private Long targetId2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_hot_relation.target_id3
     *
     * @mbg.generated
     */
    private Long targetId3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_hot_relation.target_id
     *
     * @return the value of camera_hot_relation.target_id
     *
     * @mbg.generated
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_hot_relation.target_id
     *
     * @param targetId the value for camera_hot_relation.target_id
     *
     * @mbg.generated
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_hot_relation.target_id1
     *
     * @return the value of camera_hot_relation.target_id1
     *
     * @mbg.generated
     */
    public Long getTargetId1() {
        return targetId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_hot_relation.target_id1
     *
     * @param targetId1 the value for camera_hot_relation.target_id1
     *
     * @mbg.generated
     */
    public void setTargetId1(Long targetId1) {
        this.targetId1 = targetId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_hot_relation.target_id2
     *
     * @return the value of camera_hot_relation.target_id2
     *
     * @mbg.generated
     */
    public Long getTargetId2() {
        return targetId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_hot_relation.target_id2
     *
     * @param targetId2 the value for camera_hot_relation.target_id2
     *
     * @mbg.generated
     */
    public void setTargetId2(Long targetId2) {
        this.targetId2 = targetId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_hot_relation.target_id3
     *
     * @return the value of camera_hot_relation.target_id3
     *
     * @mbg.generated
     */
    public Long getTargetId3() {
        return targetId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_hot_relation.target_id3
     *
     * @param targetId3 the value for camera_hot_relation.target_id3
     *
     * @mbg.generated
     */
    public void setTargetId3(Long targetId3) {
        this.targetId3 = targetId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", targetId=").append(targetId);
        sb.append(", targetId1=").append(targetId1);
        sb.append(", targetId2=").append(targetId2);
        sb.append(", targetId3=").append(targetId3);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CameraHotRelationDAO other = (CameraHotRelationDAO) that;
        return (this.getTargetId() == null ? other.getTargetId() == null : this.getTargetId().equals(other.getTargetId()))
            && (this.getTargetId1() == null ? other.getTargetId1() == null : this.getTargetId1().equals(other.getTargetId1()))
            && (this.getTargetId2() == null ? other.getTargetId2() == null : this.getTargetId2().equals(other.getTargetId2()))
            && (this.getTargetId3() == null ? other.getTargetId3() == null : this.getTargetId3().equals(other.getTargetId3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTargetId() == null) ? 0 : getTargetId().hashCode());
        result = prime * result + ((getTargetId1() == null) ? 0 : getTargetId1().hashCode());
        result = prime * result + ((getTargetId2() == null) ? 0 : getTargetId2().hashCode());
        result = prime * result + ((getTargetId3() == null) ? 0 : getTargetId3().hashCode());
        return result;
    }
}