package com.point.db.model;

import java.util.Date;

public class CameraCompareResultDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_compare_result.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_compare_result.full_dat_id
     *
     * @mbg.generated
     */
    private String fullDatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_compare_result.full_img_id
     *
     * @mbg.generated
     */
    private String fullImgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_compare_result.target_faces
     *
     * @mbg.generated
     */
    private String targetFaces;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_compare_result.video_id
     *
     * @mbg.generated
     */
    private String videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_compare_result.capture_time
     *
     * @mbg.generated
     */
    private Date captureTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_compare_result.dev_id
     *
     * @mbg.generated
     */
    private Long devId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_compare_result.id
     *
     * @return the value of camera_compare_result.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_compare_result.id
     *
     * @param id the value for camera_compare_result.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_compare_result.full_dat_id
     *
     * @return the value of camera_compare_result.full_dat_id
     *
     * @mbg.generated
     */
    public String getFullDatId() {
        return fullDatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_compare_result.full_dat_id
     *
     * @param fullDatId the value for camera_compare_result.full_dat_id
     *
     * @mbg.generated
     */
    public void setFullDatId(String fullDatId) {
        this.fullDatId = fullDatId == null ? null : fullDatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_compare_result.full_img_id
     *
     * @return the value of camera_compare_result.full_img_id
     *
     * @mbg.generated
     */
    public String getFullImgId() {
        return fullImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_compare_result.full_img_id
     *
     * @param fullImgId the value for camera_compare_result.full_img_id
     *
     * @mbg.generated
     */
    public void setFullImgId(String fullImgId) {
        this.fullImgId = fullImgId == null ? null : fullImgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_compare_result.target_faces
     *
     * @return the value of camera_compare_result.target_faces
     *
     * @mbg.generated
     */
    public String getTargetFaces() {
        return targetFaces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_compare_result.target_faces
     *
     * @param targetFaces the value for camera_compare_result.target_faces
     *
     * @mbg.generated
     */
    public void setTargetFaces(String targetFaces) {
        this.targetFaces = targetFaces == null ? null : targetFaces.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_compare_result.video_id
     *
     * @return the value of camera_compare_result.video_id
     *
     * @mbg.generated
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_compare_result.video_id
     *
     * @param videoId the value for camera_compare_result.video_id
     *
     * @mbg.generated
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId == null ? null : videoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_compare_result.capture_time
     *
     * @return the value of camera_compare_result.capture_time
     *
     * @mbg.generated
     */
    public Date getCaptureTime() {
        return captureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_compare_result.capture_time
     *
     * @param captureTime the value for camera_compare_result.capture_time
     *
     * @mbg.generated
     */
    public void setCaptureTime(Date captureTime) {
        this.captureTime = captureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_compare_result.dev_id
     *
     * @return the value of camera_compare_result.dev_id
     *
     * @mbg.generated
     */
    public Long getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_compare_result.dev_id
     *
     * @param devId the value for camera_compare_result.dev_id
     *
     * @mbg.generated
     */
    public void setDevId(Long devId) {
        this.devId = devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fullDatId=").append(fullDatId);
        sb.append(", fullImgId=").append(fullImgId);
        sb.append(", targetFaces=").append(targetFaces);
        sb.append(", videoId=").append(videoId);
        sb.append(", captureTime=").append(captureTime);
        sb.append(", devId=").append(devId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CameraCompareResultDAO other = (CameraCompareResultDAO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFullDatId() == null ? other.getFullDatId() == null : this.getFullDatId().equals(other.getFullDatId()))
            && (this.getFullImgId() == null ? other.getFullImgId() == null : this.getFullImgId().equals(other.getFullImgId()))
            && (this.getTargetFaces() == null ? other.getTargetFaces() == null : this.getTargetFaces().equals(other.getTargetFaces()))
            && (this.getVideoId() == null ? other.getVideoId() == null : this.getVideoId().equals(other.getVideoId()))
            && (this.getCaptureTime() == null ? other.getCaptureTime() == null : this.getCaptureTime().equals(other.getCaptureTime()))
            && (this.getDevId() == null ? other.getDevId() == null : this.getDevId().equals(other.getDevId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_compare_result
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFullDatId() == null) ? 0 : getFullDatId().hashCode());
        result = prime * result + ((getFullImgId() == null) ? 0 : getFullImgId().hashCode());
        result = prime * result + ((getTargetFaces() == null) ? 0 : getTargetFaces().hashCode());
        result = prime * result + ((getVideoId() == null) ? 0 : getVideoId().hashCode());
        result = prime * result + ((getCaptureTime() == null) ? 0 : getCaptureTime().hashCode());
        result = prime * result + ((getDevId() == null) ? 0 : getDevId().hashCode());
        return result;
    }
}