package com.point.db.model;

import java.util.ArrayList;
import java.util.List;

public class CameraHotRelationDAOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    public CameraHotRelationDAOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTargetIdIsNull() {
            addCriterion("target_id is null");
            return (Criteria) this;
        }

        public Criteria andTargetIdIsNotNull() {
            addCriterion("target_id is not null");
            return (Criteria) this;
        }

        public Criteria andTargetIdEqualTo(Long value) {
            addCriterion("target_id =", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotEqualTo(Long value) {
            addCriterion("target_id <>", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdGreaterThan(Long value) {
            addCriterion("target_id >", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdGreaterThanOrEqualTo(Long value) {
            addCriterion("target_id >=", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLessThan(Long value) {
            addCriterion("target_id <", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLessThanOrEqualTo(Long value) {
            addCriterion("target_id <=", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdIn(List<Long> values) {
            addCriterion("target_id in", values, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotIn(List<Long> values) {
            addCriterion("target_id not in", values, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdBetween(Long value1, Long value2) {
            addCriterion("target_id between", value1, value2, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotBetween(Long value1, Long value2) {
            addCriterion("target_id not between", value1, value2, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetId1IsNull() {
            addCriterion("target_id1 is null");
            return (Criteria) this;
        }

        public Criteria andTargetId1IsNotNull() {
            addCriterion("target_id1 is not null");
            return (Criteria) this;
        }

        public Criteria andTargetId1EqualTo(Long value) {
            addCriterion("target_id1 =", value, "targetId1");
            return (Criteria) this;
        }

        public Criteria andTargetId1NotEqualTo(Long value) {
            addCriterion("target_id1 <>", value, "targetId1");
            return (Criteria) this;
        }

        public Criteria andTargetId1GreaterThan(Long value) {
            addCriterion("target_id1 >", value, "targetId1");
            return (Criteria) this;
        }

        public Criteria andTargetId1GreaterThanOrEqualTo(Long value) {
            addCriterion("target_id1 >=", value, "targetId1");
            return (Criteria) this;
        }

        public Criteria andTargetId1LessThan(Long value) {
            addCriterion("target_id1 <", value, "targetId1");
            return (Criteria) this;
        }

        public Criteria andTargetId1LessThanOrEqualTo(Long value) {
            addCriterion("target_id1 <=", value, "targetId1");
            return (Criteria) this;
        }

        public Criteria andTargetId1In(List<Long> values) {
            addCriterion("target_id1 in", values, "targetId1");
            return (Criteria) this;
        }

        public Criteria andTargetId1NotIn(List<Long> values) {
            addCriterion("target_id1 not in", values, "targetId1");
            return (Criteria) this;
        }

        public Criteria andTargetId1Between(Long value1, Long value2) {
            addCriterion("target_id1 between", value1, value2, "targetId1");
            return (Criteria) this;
        }

        public Criteria andTargetId1NotBetween(Long value1, Long value2) {
            addCriterion("target_id1 not between", value1, value2, "targetId1");
            return (Criteria) this;
        }

        public Criteria andTargetId2IsNull() {
            addCriterion("target_id2 is null");
            return (Criteria) this;
        }

        public Criteria andTargetId2IsNotNull() {
            addCriterion("target_id2 is not null");
            return (Criteria) this;
        }

        public Criteria andTargetId2EqualTo(Long value) {
            addCriterion("target_id2 =", value, "targetId2");
            return (Criteria) this;
        }

        public Criteria andTargetId2NotEqualTo(Long value) {
            addCriterion("target_id2 <>", value, "targetId2");
            return (Criteria) this;
        }

        public Criteria andTargetId2GreaterThan(Long value) {
            addCriterion("target_id2 >", value, "targetId2");
            return (Criteria) this;
        }

        public Criteria andTargetId2GreaterThanOrEqualTo(Long value) {
            addCriterion("target_id2 >=", value, "targetId2");
            return (Criteria) this;
        }

        public Criteria andTargetId2LessThan(Long value) {
            addCriterion("target_id2 <", value, "targetId2");
            return (Criteria) this;
        }

        public Criteria andTargetId2LessThanOrEqualTo(Long value) {
            addCriterion("target_id2 <=", value, "targetId2");
            return (Criteria) this;
        }

        public Criteria andTargetId2In(List<Long> values) {
            addCriterion("target_id2 in", values, "targetId2");
            return (Criteria) this;
        }

        public Criteria andTargetId2NotIn(List<Long> values) {
            addCriterion("target_id2 not in", values, "targetId2");
            return (Criteria) this;
        }

        public Criteria andTargetId2Between(Long value1, Long value2) {
            addCriterion("target_id2 between", value1, value2, "targetId2");
            return (Criteria) this;
        }

        public Criteria andTargetId2NotBetween(Long value1, Long value2) {
            addCriterion("target_id2 not between", value1, value2, "targetId2");
            return (Criteria) this;
        }

        public Criteria andTargetId3IsNull() {
            addCriterion("target_id3 is null");
            return (Criteria) this;
        }

        public Criteria andTargetId3IsNotNull() {
            addCriterion("target_id3 is not null");
            return (Criteria) this;
        }

        public Criteria andTargetId3EqualTo(Long value) {
            addCriterion("target_id3 =", value, "targetId3");
            return (Criteria) this;
        }

        public Criteria andTargetId3NotEqualTo(Long value) {
            addCriterion("target_id3 <>", value, "targetId3");
            return (Criteria) this;
        }

        public Criteria andTargetId3GreaterThan(Long value) {
            addCriterion("target_id3 >", value, "targetId3");
            return (Criteria) this;
        }

        public Criteria andTargetId3GreaterThanOrEqualTo(Long value) {
            addCriterion("target_id3 >=", value, "targetId3");
            return (Criteria) this;
        }

        public Criteria andTargetId3LessThan(Long value) {
            addCriterion("target_id3 <", value, "targetId3");
            return (Criteria) this;
        }

        public Criteria andTargetId3LessThanOrEqualTo(Long value) {
            addCriterion("target_id3 <=", value, "targetId3");
            return (Criteria) this;
        }

        public Criteria andTargetId3In(List<Long> values) {
            addCriterion("target_id3 in", values, "targetId3");
            return (Criteria) this;
        }

        public Criteria andTargetId3NotIn(List<Long> values) {
            addCriterion("target_id3 not in", values, "targetId3");
            return (Criteria) this;
        }

        public Criteria andTargetId3Between(Long value1, Long value2) {
            addCriterion("target_id3 between", value1, value2, "targetId3");
            return (Criteria) this;
        }

        public Criteria andTargetId3NotBetween(Long value1, Long value2) {
            addCriterion("target_id3 not between", value1, value2, "targetId3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table camera_hot_relation
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}