package com.point.db.model;

public class HotFrontDeviceDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_front_device.dev_id
     *
     * @mbg.generated
     */
    private Long devId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_front_device.group_id
     *
     * @mbg.generated
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_front_device.dev_name
     *
     * @mbg.generated
     */
    private String devName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_front_device.dev_type
     *
     * @mbg.generated
     */
    private Byte devType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_front_device.dev_num
     *
     * @mbg.generated
     */
    private String devNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_front_device.ip_addr
     *
     * @mbg.generated
     */
    private String ipAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_front_device.ipv6_addr
     *
     * @mbg.generated
     */
    private String ipv6Addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_front_device.port
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_front_device.lng
     *
     * @mbg.generated
     */
    private String lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_front_device.lat
     *
     * @mbg.generated
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_front_device.place
     *
     * @mbg.generated
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_front_device.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_front_device.dev_id
     *
     * @return the value of hot_front_device.dev_id
     *
     * @mbg.generated
     */
    public Long getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_front_device.dev_id
     *
     * @param devId the value for hot_front_device.dev_id
     *
     * @mbg.generated
     */
    public void setDevId(Long devId) {
        this.devId = devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_front_device.group_id
     *
     * @return the value of hot_front_device.group_id
     *
     * @mbg.generated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_front_device.group_id
     *
     * @param groupId the value for hot_front_device.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_front_device.dev_name
     *
     * @return the value of hot_front_device.dev_name
     *
     * @mbg.generated
     */
    public String getDevName() {
        return devName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_front_device.dev_name
     *
     * @param devName the value for hot_front_device.dev_name
     *
     * @mbg.generated
     */
    public void setDevName(String devName) {
        this.devName = devName == null ? null : devName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_front_device.dev_type
     *
     * @return the value of hot_front_device.dev_type
     *
     * @mbg.generated
     */
    public Byte getDevType() {
        return devType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_front_device.dev_type
     *
     * @param devType the value for hot_front_device.dev_type
     *
     * @mbg.generated
     */
    public void setDevType(Byte devType) {
        this.devType = devType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_front_device.dev_num
     *
     * @return the value of hot_front_device.dev_num
     *
     * @mbg.generated
     */
    public String getDevNum() {
        return devNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_front_device.dev_num
     *
     * @param devNum the value for hot_front_device.dev_num
     *
     * @mbg.generated
     */
    public void setDevNum(String devNum) {
        this.devNum = devNum == null ? null : devNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_front_device.ip_addr
     *
     * @return the value of hot_front_device.ip_addr
     *
     * @mbg.generated
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_front_device.ip_addr
     *
     * @param ipAddr the value for hot_front_device.ip_addr
     *
     * @mbg.generated
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_front_device.ipv6_addr
     *
     * @return the value of hot_front_device.ipv6_addr
     *
     * @mbg.generated
     */
    public String getIpv6Addr() {
        return ipv6Addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_front_device.ipv6_addr
     *
     * @param ipv6Addr the value for hot_front_device.ipv6_addr
     *
     * @mbg.generated
     */
    public void setIpv6Addr(String ipv6Addr) {
        this.ipv6Addr = ipv6Addr == null ? null : ipv6Addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_front_device.port
     *
     * @return the value of hot_front_device.port
     *
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_front_device.port
     *
     * @param port the value for hot_front_device.port
     *
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_front_device.lng
     *
     * @return the value of hot_front_device.lng
     *
     * @mbg.generated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_front_device.lng
     *
     * @param lng the value for hot_front_device.lng
     *
     * @mbg.generated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_front_device.lat
     *
     * @return the value of hot_front_device.lat
     *
     * @mbg.generated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_front_device.lat
     *
     * @param lat the value for hot_front_device.lat
     *
     * @mbg.generated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_front_device.place
     *
     * @return the value of hot_front_device.place
     *
     * @mbg.generated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_front_device.place
     *
     * @param place the value for hot_front_device.place
     *
     * @mbg.generated
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_front_device.description
     *
     * @return the value of hot_front_device.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_front_device.description
     *
     * @param description the value for hot_front_device.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", devId=").append(devId);
        sb.append(", groupId=").append(groupId);
        sb.append(", devName=").append(devName);
        sb.append(", devType=").append(devType);
        sb.append(", devNum=").append(devNum);
        sb.append(", ipAddr=").append(ipAddr);
        sb.append(", ipv6Addr=").append(ipv6Addr);
        sb.append(", port=").append(port);
        sb.append(", lng=").append(lng);
        sb.append(", lat=").append(lat);
        sb.append(", place=").append(place);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HotFrontDeviceDAO other = (HotFrontDeviceDAO) that;
        return (this.getDevId() == null ? other.getDevId() == null : this.getDevId().equals(other.getDevId()))
            && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getDevName() == null ? other.getDevName() == null : this.getDevName().equals(other.getDevName()))
            && (this.getDevType() == null ? other.getDevType() == null : this.getDevType().equals(other.getDevType()))
            && (this.getDevNum() == null ? other.getDevNum() == null : this.getDevNum().equals(other.getDevNum()))
            && (this.getIpAddr() == null ? other.getIpAddr() == null : this.getIpAddr().equals(other.getIpAddr()))
            && (this.getIpv6Addr() == null ? other.getIpv6Addr() == null : this.getIpv6Addr().equals(other.getIpv6Addr()))
            && (this.getPort() == null ? other.getPort() == null : this.getPort().equals(other.getPort()))
            && (this.getLng() == null ? other.getLng() == null : this.getLng().equals(other.getLng()))
            && (this.getLat() == null ? other.getLat() == null : this.getLat().equals(other.getLat()))
            && (this.getPlace() == null ? other.getPlace() == null : this.getPlace().equals(other.getPlace()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDevId() == null) ? 0 : getDevId().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getDevName() == null) ? 0 : getDevName().hashCode());
        result = prime * result + ((getDevType() == null) ? 0 : getDevType().hashCode());
        result = prime * result + ((getDevNum() == null) ? 0 : getDevNum().hashCode());
        result = prime * result + ((getIpAddr() == null) ? 0 : getIpAddr().hashCode());
        result = prime * result + ((getIpv6Addr() == null) ? 0 : getIpv6Addr().hashCode());
        result = prime * result + ((getPort() == null) ? 0 : getPort().hashCode());
        result = prime * result + ((getLng() == null) ? 0 : getLng().hashCode());
        result = prime * result + ((getLat() == null) ? 0 : getLat().hashCode());
        result = prime * result + ((getPlace() == null) ? 0 : getPlace().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }
}