package com.point.db.model;

import java.util.Date;

public class HotNumInfoDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_num_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_num_info.imsi
     *
     * @mbg.generated
     */
    private String imsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_num_info.imei
     *
     * @mbg.generated
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_num_info.isdn
     *
     * @mbg.generated
     */
    private String isdn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_num_info.mode
     *
     * @mbg.generated
     */
    private String mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_num_info.capture_time
     *
     * @mbg.generated
     */
    private Date captureTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_num_info.target_id
     *
     * @mbg.generated
     */
    private Long targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_num_info.dev_id
     *
     * @mbg.generated
     */
    private Long devId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_num_info.id
     *
     * @return the value of hot_num_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_num_info.id
     *
     * @param id the value for hot_num_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_num_info.imsi
     *
     * @return the value of hot_num_info.imsi
     *
     * @mbg.generated
     */
    public String getImsi() {
        return imsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_num_info.imsi
     *
     * @param imsi the value for hot_num_info.imsi
     *
     * @mbg.generated
     */
    public void setImsi(String imsi) {
        this.imsi = imsi == null ? null : imsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_num_info.imei
     *
     * @return the value of hot_num_info.imei
     *
     * @mbg.generated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_num_info.imei
     *
     * @param imei the value for hot_num_info.imei
     *
     * @mbg.generated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_num_info.isdn
     *
     * @return the value of hot_num_info.isdn
     *
     * @mbg.generated
     */
    public String getIsdn() {
        return isdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_num_info.isdn
     *
     * @param isdn the value for hot_num_info.isdn
     *
     * @mbg.generated
     */
    public void setIsdn(String isdn) {
        this.isdn = isdn == null ? null : isdn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_num_info.mode
     *
     * @return the value of hot_num_info.mode
     *
     * @mbg.generated
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_num_info.mode
     *
     * @param mode the value for hot_num_info.mode
     *
     * @mbg.generated
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_num_info.capture_time
     *
     * @return the value of hot_num_info.capture_time
     *
     * @mbg.generated
     */
    public Date getCaptureTime() {
        return captureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_num_info.capture_time
     *
     * @param captureTime the value for hot_num_info.capture_time
     *
     * @mbg.generated
     */
    public void setCaptureTime(Date captureTime) {
        this.captureTime = captureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_num_info.target_id
     *
     * @return the value of hot_num_info.target_id
     *
     * @mbg.generated
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_num_info.target_id
     *
     * @param targetId the value for hot_num_info.target_id
     *
     * @mbg.generated
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_num_info.dev_id
     *
     * @return the value of hot_num_info.dev_id
     *
     * @mbg.generated
     */
    public Long getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_num_info.dev_id
     *
     * @param devId the value for hot_num_info.dev_id
     *
     * @mbg.generated
     */
    public void setDevId(Long devId) {
        this.devId = devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", imsi=").append(imsi);
        sb.append(", imei=").append(imei);
        sb.append(", isdn=").append(isdn);
        sb.append(", mode=").append(mode);
        sb.append(", captureTime=").append(captureTime);
        sb.append(", targetId=").append(targetId);
        sb.append(", devId=").append(devId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HotNumInfoDAO other = (HotNumInfoDAO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getImsi() == null ? other.getImsi() == null : this.getImsi().equals(other.getImsi()))
            && (this.getImei() == null ? other.getImei() == null : this.getImei().equals(other.getImei()))
            && (this.getIsdn() == null ? other.getIsdn() == null : this.getIsdn().equals(other.getIsdn()))
            && (this.getMode() == null ? other.getMode() == null : this.getMode().equals(other.getMode()))
            && (this.getCaptureTime() == null ? other.getCaptureTime() == null : this.getCaptureTime().equals(other.getCaptureTime()))
            && (this.getTargetId() == null ? other.getTargetId() == null : this.getTargetId().equals(other.getTargetId()))
            && (this.getDevId() == null ? other.getDevId() == null : this.getDevId().equals(other.getDevId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_num_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getImsi() == null) ? 0 : getImsi().hashCode());
        result = prime * result + ((getImei() == null) ? 0 : getImei().hashCode());
        result = prime * result + ((getIsdn() == null) ? 0 : getIsdn().hashCode());
        result = prime * result + ((getMode() == null) ? 0 : getMode().hashCode());
        result = prime * result + ((getCaptureTime() == null) ? 0 : getCaptureTime().hashCode());
        result = prime * result + ((getTargetId() == null) ? 0 : getTargetId().hashCode());
        result = prime * result + ((getDevId() == null) ? 0 : getDevId().hashCode());
        return result;
    }
}