package com.point.db.model;

import java.util.Date;

public class HotTargetInfoDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_target_info.target_id
     *
     * @mbg.generated
     */
    private Long targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_target_info.target_name
     *
     * @mbg.generated
     */
    private String targetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_target_info.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_target_info.imsi
     *
     * @mbg.generated
     */
    private String imsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_target_info.imei
     *
     * @mbg.generated
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_target_info.isdn
     *
     * @mbg.generated
     */
    private String isdn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_target_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_target_info.operator_id
     *
     * @mbg.generated
     */
    private Long operatorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_target_info.target_id
     *
     * @return the value of hot_target_info.target_id
     *
     * @mbg.generated
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_target_info.target_id
     *
     * @param targetId the value for hot_target_info.target_id
     *
     * @mbg.generated
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_target_info.target_name
     *
     * @return the value of hot_target_info.target_name
     *
     * @mbg.generated
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_target_info.target_name
     *
     * @param targetName the value for hot_target_info.target_name
     *
     * @mbg.generated
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName == null ? null : targetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_target_info.desc
     *
     * @return the value of hot_target_info.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_target_info.desc
     *
     * @param desc the value for hot_target_info.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_target_info.imsi
     *
     * @return the value of hot_target_info.imsi
     *
     * @mbg.generated
     */
    public String getImsi() {
        return imsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_target_info.imsi
     *
     * @param imsi the value for hot_target_info.imsi
     *
     * @mbg.generated
     */
    public void setImsi(String imsi) {
        this.imsi = imsi == null ? null : imsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_target_info.imei
     *
     * @return the value of hot_target_info.imei
     *
     * @mbg.generated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_target_info.imei
     *
     * @param imei the value for hot_target_info.imei
     *
     * @mbg.generated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_target_info.isdn
     *
     * @return the value of hot_target_info.isdn
     *
     * @mbg.generated
     */
    public String getIsdn() {
        return isdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_target_info.isdn
     *
     * @param isdn the value for hot_target_info.isdn
     *
     * @mbg.generated
     */
    public void setIsdn(String isdn) {
        this.isdn = isdn == null ? null : isdn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_target_info.create_time
     *
     * @return the value of hot_target_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_target_info.create_time
     *
     * @param createTime the value for hot_target_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_target_info.operator_id
     *
     * @return the value of hot_target_info.operator_id
     *
     * @mbg.generated
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_target_info.operator_id
     *
     * @param operatorId the value for hot_target_info.operator_id
     *
     * @mbg.generated
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", targetId=").append(targetId);
        sb.append(", targetName=").append(targetName);
        sb.append(", desc=").append(desc);
        sb.append(", imsi=").append(imsi);
        sb.append(", imei=").append(imei);
        sb.append(", isdn=").append(isdn);
        sb.append(", createTime=").append(createTime);
        sb.append(", operatorId=").append(operatorId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HotTargetInfoDAO other = (HotTargetInfoDAO) that;
        return (this.getTargetId() == null ? other.getTargetId() == null : this.getTargetId().equals(other.getTargetId()))
            && (this.getTargetName() == null ? other.getTargetName() == null : this.getTargetName().equals(other.getTargetName()))
            && (this.getDesc() == null ? other.getDesc() == null : this.getDesc().equals(other.getDesc()))
            && (this.getImsi() == null ? other.getImsi() == null : this.getImsi().equals(other.getImsi()))
            && (this.getImei() == null ? other.getImei() == null : this.getImei().equals(other.getImei()))
            && (this.getIsdn() == null ? other.getIsdn() == null : this.getIsdn().equals(other.getIsdn()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getOperatorId() == null ? other.getOperatorId() == null : this.getOperatorId().equals(other.getOperatorId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTargetId() == null) ? 0 : getTargetId().hashCode());
        result = prime * result + ((getTargetName() == null) ? 0 : getTargetName().hashCode());
        result = prime * result + ((getDesc() == null) ? 0 : getDesc().hashCode());
        result = prime * result + ((getImsi() == null) ? 0 : getImsi().hashCode());
        result = prime * result + ((getImei() == null) ? 0 : getImei().hashCode());
        result = prime * result + ((getIsdn() == null) ? 0 : getIsdn().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getOperatorId() == null) ? 0 : getOperatorId().hashCode());
        return result;
    }
}