package com.point.db.dao;

import com.point.db.model.CameraTargetFaceDAO;
import com.point.db.model.CameraTargetFaceDAOExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CameraTargetFaceDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_target_face
     *
     * @mbg.generated
     */
    long countByExample(CameraTargetFaceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_target_face
     *
     * @mbg.generated
     */
    int deleteByExample(CameraTargetFaceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_target_face
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long targetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_target_face
     *
     * @mbg.generated
     */
    int insert(CameraTargetFaceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_target_face
     *
     * @mbg.generated
     */
    int insertSelective(CameraTargetFaceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_target_face
     *
     * @mbg.generated
     */
    List<CameraTargetFaceDAO> selectByExample(CameraTargetFaceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_target_face
     *
     * @mbg.generated
     */
    CameraTargetFaceDAO selectByPrimaryKey(Long targetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_target_face
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CameraTargetFaceDAO record, @Param("example") CameraTargetFaceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_target_face
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CameraTargetFaceDAO record, @Param("example") CameraTargetFaceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_target_face
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CameraTargetFaceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_target_face
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CameraTargetFaceDAO record);
}