package com.point.db.dao;

import com.point.db.model.CameraHotRelationDAO;
import com.point.db.model.CameraHotRelationDAOExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CameraHotRelationDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    long countByExample(CameraHotRelationDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    int deleteByExample(CameraHotRelationDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long targetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    int insert(CameraHotRelationDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    int insertSelective(CameraHotRelationDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    List<CameraHotRelationDAO> selectByExample(CameraHotRelationDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    CameraHotRelationDAO selectByPrimaryKey(Long targetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CameraHotRelationDAO record, @Param("example") CameraHotRelationDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CameraHotRelationDAO record, @Param("example") CameraHotRelationDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CameraHotRelationDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_hot_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CameraHotRelationDAO record);
}