package com.point.db.dao;

import com.point.db.model.HotFrontDeviceDAO;
import com.point.db.model.HotFrontDeviceDAOExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface HotFrontDeviceDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    long countByExample(HotFrontDeviceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int deleteByExample(HotFrontDeviceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long devId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int insert(HotFrontDeviceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int insertSelective(HotFrontDeviceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    List<HotFrontDeviceDAO> selectByExample(HotFrontDeviceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    HotFrontDeviceDAO selectByPrimaryKey(Long devId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HotFrontDeviceDAO record, @Param("example") HotFrontDeviceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HotFrontDeviceDAO record, @Param("example") HotFrontDeviceDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HotFrontDeviceDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_front_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HotFrontDeviceDAO record);
}