package com.point.db.dao;

import com.point.db.model.HotTargetInfoDAO;
import com.point.db.model.HotTargetInfoDAOExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface HotTargetInfoDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    long countByExample(HotTargetInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int deleteByExample(HotTargetInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long targetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int insert(HotTargetInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int insertSelective(HotTargetInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    List<HotTargetInfoDAO> selectByExample(HotTargetInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    HotTargetInfoDAO selectByPrimaryKey(Long targetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HotTargetInfoDAO record, @Param("example") HotTargetInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HotTargetInfoDAO record, @Param("example") HotTargetInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HotTargetInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_target_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HotTargetInfoDAO record);
}