package com.point.db.dao;

import com.point.db.model.OperatorInfoDAO;
import com.point.db.model.OperatorInfoDAOExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OperatorInfoDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_info
     *
     * @mbg.generated
     */
    long countByExample(OperatorInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_info
     *
     * @mbg.generated
     */
    int deleteByExample(OperatorInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long operatorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_info
     *
     * @mbg.generated
     */
    int insert(OperatorInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_info
     *
     * @mbg.generated
     */
    int insertSelective(OperatorInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_info
     *
     * @mbg.generated
     */
    List<OperatorInfoDAO> selectByExample(OperatorInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_info
     *
     * @mbg.generated
     */
    OperatorInfoDAO selectByPrimaryKey(Long operatorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OperatorInfoDAO record, @Param("example") OperatorInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OperatorInfoDAO record, @Param("example") OperatorInfoDAOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OperatorInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OperatorInfoDAO record);
}